//Authentication
export const CHECK_AUTH = 'CHECK_AUTH'

//Fetches
export const FETCH_FAVORITES = 'FETCH_FAVORITES'
export const FETCH_POPULAR = 'FETCH_POPULAR'
export const FETCH_NEW = 'FETCH_NEW'
export const FETCH_COCKTAILS = 'FETCH_COCKTAILS'
export const FETCH_SHOTS = 'FETCH_SHOTS'
export const FETCH_PUNCHES = 'FETCH_PUNCHES'

//Loading
export const LOADING_FAVORITES = 'LOADING_FAVORITES'
export const LOADING_POPULAR = 'LOADING_POPULAR'
export const LOADING_NEW = 'LOADING_NEW'
export const LOADING_COCKTAILS = 'LOADING_COCKTAILS'
export const LOADING_SHOTS = 'LOADING_SHOTS'
export const LOADING_PUNCHES = 'LOADING_PUNCHES'
export const REFRESHING = 'REFRESHING'
